version: "3.7"

# services:
#   mongodb:
#     image: mongo
#     container_name: mongo
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
#     ports:
#       - 27017:27017


services:
  postgres:
    image: postgres:13
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
    # volumes:
    #   - ./data_db:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - type: bind
  #       source: ./src
  #       target: /app/src
  #   depends_on:
  #     - postgres

  